using Pkg
Pkg.add("GaloisFields")
Pkg.add("Polynomials")
Pkg.add("Formatting")
Pkg.add("Distributions")
Pkg.add("LaTeXStrings")
Pkg.add("Noise")
Pkg.add("Plots")
Pkg.add("SpecialFunctions")
Pkg.add("StatsBase")
Pkg.add("SymPy")
